[versions]
kotlin = "1.9.25"

[libraries]
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin" }

dependency-versions-gradle = { module = "com.github.ben-manes:gradle-versions-plugin", version = "0.51.0" }
kotlin-gradle = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
ktlint-gradle = { module = "org.jlleitschuh.gradle:ktlint-gradle", version = "12.3.0" }

[plugins]
cyclonedx-bom = { id = "org.cyclonedx.bom", version = "2.3.1" }
